# Page settings

baseurl = "http://gallas-design.net/"
languageCode = "en-us"
title = "Gallas Design"
copyright = "© Gallas Design"
googleAnalytics = "UA-xxxxxxxx-x"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "hugo-theme-doors"

disableRSS = true
disableSitemap = true
disable404 = true

# Site information
[params]
description = ""
ogimage = ""

# Project section
[params.projects]

[[params.projects.list]]
title = "Gallas Design"
#url = ""
description = "Exploring industrial creative home decor"
image = "images/CandleHolder_01.jpeg"
w = "780"
h = "518"

# Subproject section
[params.subprojects]

[[params.subprojects.list]]
title = "Seasonal creations"
url = "#"
description = "Holiday creations"
image = "images/CandleHolder_11.jpeg"
w = "780"
h = "522"

[[params.subprojects.list]]
title = "The Candle Holders"
url = "#"
description = "Copper tubing Candle Holders"
image = "images/CandleHolder_10.jpeg"
w = "780"
h = "1380"

[[params.subprojects.list]]
title = "Latest project"
url = "#"
description = "Winter time"
image = "images/CandleHolder_02.jpeg"
w = "780"
h = "1380"

# Contact section
[params.contact]
description = "I would like to hear from you. Please contact me via Instagram."
#facebook = "bla bla bla"
instagram = "https://www.instagram.com/designgallas/"

